name: Build and Push

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build and push'
        required: false
env:
      DOCKER_HUB_PAT: ${{ env.DOCKER_HUB_PAT }}
jobs:
  build-push:
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Push
      run: |
        # Build the image
        docker build -t jclaridad07/pinoymassagetestapi:v1.0.2 .
        # Login to your Docker Hub registry
        echo $DOCKER_HUB_PAT | docker login --username jclaridad07 --password-stdin
        # Push the image to Docker Hub
        docker push jclaridad07/pinoymassagetestapi:v1.0.2
